/* tslint:disable */

/* eslint-disable */

/**
 * test-front API
 * test-front API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { exists, mapValues } from "../runtime";

/**
 *
 * @export
 * @interface ApiKeyDto
 */
export interface ApiKeyDto {
  /**
   *
   * @type {string}
   * @memberof ApiKeyDto
   */
  value: string;
}

/**
 * Check if a given object implements the ApiKeyDto interface.
 */
export function instanceOfApiKeyDto(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "value" in value;

  return isInstance;
}

export function ApiKeyDtoFromJSON(json: any): ApiKeyDto {
  return ApiKeyDtoFromJSONTyped(json, false);
}

export function ApiKeyDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ApiKeyDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    value: json["value"],
  };
}

export function ApiKeyDtoToJSON(value?: ApiKeyDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    value: value.value,
  };
}
