/* tslint:disable */

/* eslint-disable */

/**
 * test-front API
 * test-front API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { exists, mapValues } from "../runtime";

/**
 *
 * @export
 * @interface ImageDto
 */
export interface ImageDto {
  /**
   *
   * @type {string}
   * @memberof ImageDto
   */
  id: string;
  /**
   *
   * @type {string}
   * @memberof ImageDto
   */
  url: string;
  /**
   *
   * @type {string}
   * @memberof ImageDto
   */
  width: string;
  /**
   *
   * @type {string}
   * @memberof ImageDto
   */
  height: string;
}

/**
 * Check if a given object implements the ImageDto interface.
 */
export function instanceOfImageDto(value: object): boolean {
  let isInstance = true;
  isInstance = isInstance && "id" in value;
  isInstance = isInstance && "url" in value;
  isInstance = isInstance && "width" in value;
  isInstance = isInstance && "height" in value;

  return isInstance;
}

export function ImageDtoFromJSON(json: any): ImageDto {
  return ImageDtoFromJSONTyped(json, false);
}

export function ImageDtoFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): ImageDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: json["id"],
    url: json["url"],
    width: json["width"],
    height: json["height"],
  };
}

export function ImageDtoToJSON(value?: ImageDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    url: value.url,
    width: value.width,
    height: value.height,
  };
}
