/* tslint:disable */

/* eslint-disable */

/**
 * test-front API
 * test-front API
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import type { ProfileDto, UpdateProfileDto } from "../models/index";
import {
  ProfileDtoFromJSON,
  ProfileDtoToJSON,
  UpdateProfileDtoFromJSON,
  UpdateProfileDtoToJSON,
} from "../models/index";
import * as runtime from "../runtime";

export interface UpdateMyProfileRequest {
  updateProfileDto: UpdateProfileDto;
}

/**
 *
 */
export class ProfileApi extends runtime.BaseAPI {
  /**
   */
  async myProfileRaw(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ProfileDto>> {
    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["X-API-KEY"] = this.configuration.apiKey("X-API-KEY"); // X-API-KEY authentication
    }

    const response = await this.request(
      {
        path: `/api/profile`,
        method: "GET",
        headers: headerParameters,
        query: queryParameters,
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ProfileDtoFromJSON(jsonValue)
    );
  }

  /**
   */
  async myProfile(
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ProfileDto> {
    const response = await this.myProfileRaw(initOverrides);
    return await response.value();
  }

  /**
   */
  async updateMyProfileRaw(
    requestParameters: UpdateMyProfileRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<runtime.ApiResponse<ProfileDto>> {
    if (
      requestParameters.updateProfileDto === null ||
      requestParameters.updateProfileDto === undefined
    ) {
      throw new runtime.RequiredError(
        "updateProfileDto",
        "Required parameter requestParameters.updateProfileDto was null or undefined when calling updateMyProfile."
      );
    }

    const queryParameters: any = {};

    const headerParameters: runtime.HTTPHeaders = {};

    headerParameters["Content-Type"] = "application/json";

    if (this.configuration && this.configuration.apiKey) {
      headerParameters["X-API-KEY"] = this.configuration.apiKey("X-API-KEY"); // X-API-KEY authentication
    }

    const response = await this.request(
      {
        path: `/api/profile`,
        method: "PATCH",
        headers: headerParameters,
        query: queryParameters,
        body: UpdateProfileDtoToJSON(requestParameters.updateProfileDto),
      },
      initOverrides
    );

    return new runtime.JSONApiResponse(response, (jsonValue) =>
      ProfileDtoFromJSON(jsonValue)
    );
  }

  /**
   */
  async updateMyProfile(
    requestParameters: UpdateMyProfileRequest,
    initOverrides?: RequestInit | runtime.InitOverrideFunction
  ): Promise<ProfileDto> {
    const response = await this.updateMyProfileRaw(
      requestParameters,
      initOverrides
    );
    return await response.value();
  }
}
